# Generated by Django 5.1.1 on 2024-09-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dietary_restrictions',
            field=models.TextField(default=''),
        ),
    ]
