# Generated by Django 5.1.1 on 2024-09-19 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='preperation_time',
            new_name='preparation_time',
        ),
    ]
