# Generated by Django 5.1.1 on 2024-09-19 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_preperation_time_recipe_preparation_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='nutrition_fact',
            new_name='nutrition_facts',
        ),
    ]
