# Generated by Django 5.1.1 on 2024-09-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_nutrition_fact_recipe_nutrition_facts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_foods', models.JSONField()),
                ('description', models.TextField()),
            ],
            options={
                'indexes': [models.Index(fields=['description'], name='api_ingredi_descrip_ceecf4_idx')],
            },
        ),
    ]
